#version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: smbstore
      MYSQL_ROOT_PASSWORD: smbstore
      MYSQL_PASSWORD: smbstore
#    command: --default-authentication-plugin=mysql_native_password
#    restart: unless-stopped
    volumes:
      - ./db_data:/usr/data
    ports:
      - 33069:3306
  web:
    build:
      context: .
#      args:
#        uid: ${UID}
#    environment:
#      - APACHE_RUN_USER=#${UID}
#      - APACHE_RUN_GROUP=#${UID}
#    restart: unless-stopped
    volumes:
      - ./:/var/www/html
      - ./apache_log:/var/log/apache2
    ports:
      - 8089:80
    depends_on:
      - db
    links:
      - db
volumes:
  db_data:
#  src:
